export type currentModalType =
  | 'login'
  | 'register'
  | 'forgot-password'
  | 'reset-password'
  | 'account-activated'
  | 'password-changed'
  | 'link-expired'
  | 'register-notification'
  | 'edit-notification'
  | 'forgot-password-notification'
  | 'confirmation-notification'
  | 'add-movie'
  | 'add-quote'
  | 'quote-view'
  | 'edit-quote'
  | 'edit-movie'
  | null;
