name: 'Deploy on server'
on:
  push:
    branches:
      - main
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: 'Set ssh key'
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: 'Deploy to Server'
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << EOF
            cd apps
            cd nextjs-folder-structure-example
            git pull
            npm ci
            npm run build
            pm2 restart nextjs-example-process
          EOF
